/* KKPhim Torrent v4.6.1 - File 3/3 */
(function(){ 'use strict';
window.__KKPhimParts = window.__KKPhimParts || { loaded: { ui: false, parser: false, torrent: false } };
if(!window.KKPhimTorrent) window.KKPhimTorrent = {};

var TIO_BASE='https://torrentio.strem.fun';

function ls(){try{return JSON.parse(localStorage.getItem('kkphim_settings'))||{};}catch(e){return{};}}
function E(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function pd(n){return(n<10?'0':'')+n;}
function dly(ms){return new Promise(function(r){setTimeout(r,ms);});}
function tsHost(){return ls().torrserver_host||'';} function tsPass(){return ls().torrserver_password||'';}
function tioConf(){return ls().torrentio_config||'';} function aioUrl(){return ls().aio_url||'';}
function tEngine(){return ls().torrent_engine||'torrentio';}

function cTio(raw){ if(!raw)return''; raw=String(raw).trim(); if(!raw)return ''; var m=raw.match(/torrentio\.strem\.fun\/([^\/]+?)\/manifest\.json/i); if(m)return m[1]; m=raw.match(/torrentio\.strem\.fun\/([^\/]+?)\/stream\//i); if(m)return m[1]; if(raw.indexOf('torrentio.strem.fun')>-1){ raw=raw.replace(/^https?:\/\/torrentio\.strem\.fun\/?/i,'').replace(/\/(manifest\.json|stream\/.*|configure\/?.*)?$/i,'').replace(/^\/+|\/+$/g,''); if(raw&&raw.indexOf('=')>-1)return raw.replace(/\|/g,'%7C'); return''; } raw=raw.replace(/^\/+|\/+$/g,'').replace(/\|/g,'%7C'); return raw.indexOf('=')===-1?'':raw; }
function cAio(raw){ if(!raw)return ''; return String(raw).trim().replace(/\/manifest\.json\s*$/i,'').replace(/\/+$/,''); }
function tioU(type,imdb,s,e){ var t=type==='tv'?'series':'movie'; var id=imdb; if(type==='tv'&&s&&e)id=imdb+':'+s+':'+e; var c=cTio(tioConf()); return TIO_BASE+(c?'/'+c:'')+'/stream/'+t+'/'+id+'.json'; }
function aioU(type,imdb,s,e){ var base=cAio(aioUrl()); if(!base)return''; var t=type==='tv'?'series':'movie'; var id=imdb; if(type==='tv'&&s&&e)id=imdb+':'+s+':'+e; return base+'/stream/'+t+'/'+id+'.json'; }
async function fStreams(type,imdb,s,e){ var eng=tEngine(); var url; if(eng==='aio'){url=aioU(type,imdb,s,e);if(!url)throw new Error('Chua cau hinh AIO');} else{url=tioU(type,imdb,s,e);} var r=await fetch(url); if(!r.ok)throw new Error(eng+' '+r.status); var d=await r.json(); return(d.streams||[]).map(pStream); }

function pStream(st){ var rawName=String(st.name||''); var rawDesc=String(st.description||''); var rawTitle=String(st.title||''); var rawAll=rawName+'\n'+rawDesc+'\n'+rawTitle; var name=rawName.split('\n')[0].trim()||rawTitle.split('\n')[0].trim()||'?'; var qual=''; var qm=rawAll.match(/\b(2160p|4K|UHD|1080p|720p|480p|HDR10?|BluRay|WEB-?DL|HDTV|CAM)\b/i); if(qm)qual=qm[1].toUpperCase(); var size=''; var sP=[/\s*([\d.,]+\s*(?:TB|GB|GiB|MB|MiB))/i,/\b([\d.,]+)\s*(GB|GiB)\b/i,/\b([\d.,]+)\s*(MB|MiB)\b/i]; for(var i=0;i<sP.length;i++){ var sm=rawAll.match(sP[i]); if(sm){size=sm[2]?sm[1]+''+sm[2]:sm[1].trim();break;} } var seeds=''; var sdP=[/\s*(?:Seeders?:?\s*)?(\d+)/i,/(\d+)\s*seed/i]; for(var j=0;j<sdP.length;j++){ var se=rawAll.match(sdP[j]); if(se){seeds=se[1];break;} } if(st.behaviorHints&&typeof st.behaviorHints==='object'){ var bh=st.behaviorHints; if(!size&&bh.videoSize){ var bytes=Number(bh.videoSize); if(!isNaN(bytes)&&bytes>0){ if(bytes>=1073741824)size=(bytes/1073741824).toFixed(1)+' GB'; else if(bytes>=1048576)size=(bytes/1048576).toFixed(0)+' MB'; } } } return{name:name,infoHash:st.infoHash||'',fileIdx:st.fileIdx,url:st.url||'',size:size,seeds:seeds,quality:qual}; }
function fmtStream(s){ var parts=[s.name]; if(s.quality&&s.name.toUpperCase().indexOf(s.quality)===-1)parts[0]+='[ '+s.quality+' ]'; var meta=[]; if(s.size)meta.push('Size:'+s.size); if(s.seeds)meta.push('Seeds:'+s.seeds); if(meta.length)parts.push(meta.join(' | ')); return parts.join('\n'); }

function bMag(h){ var m='magnet:?xt=urn:btih:'+h; ['udp://tracker.opentrackr.org:1337/announce','udp://open.stealth.si:80/announce'].forEach(function(t){ m+='&tr='+encodeURIComponent(t); }); return m; }
function tsU(p){ var h=tsHost(); if(!h)return ''; h=h.replace(/\/+$/,''); if(h.indexOf('http')!==0)h='http://'+h; return h+p; }
function tsH(){ var h={'Content-Type':'application/json'}; var pw=tsPass(); if(pw)h['Authorization']='Basic '+btoa('admin:'+pw); return h; }

async function playTS(stream,title,poster,fi){ if(!tsHost()){Lampa.Noty.show('Chua cau hinh TS!');return;} Lampa.Noty.show('Gui TS...'); try{ var u=tsU('/torrents'); var r=await fetch(u, {method:'POST',headers:tsH(),body:JSON.stringify({action:'add',link:bMag(stream.infoHash),title:title||'',poster:poster||'',save_to_db:false})}); if(!r.ok)throw new Error('TS:'+r.status); var td=await r.json(); var hash=td.hash||stream.infoHash; await dly(2000); var info=null; var rt=0; while(rt<3){ try{ var r2=await fetch(u, {method:'POST',headers:tsH(),body:JSON.stringify({action:'get',hash:hash})}); info=await r2.json(); if(info&&info.file_stats&&info.file_stats.length)break; }catch(e){} rt++; await dly(1500); } var files=[]; if(info&&info.file_stats){ files=info.file_stats.filter(function(f){ return(f.path||'').toLowerCase().match(/\.(mp4|mkv|avi|mov|flv|webm|ts|m2ts)$/); }).sort(function(a,b){return(a.id||0)-(b.id||0);}); } var playFile=function(fileUrl){Lampa.Player.play({title:title,url:fileUrl});}; if(!files.length)playFile(tsU('/stream/fname?link='+hash+'&index=0&play')); else if(files.length===1)playFile(tsU('/stream/fname?link='+hash+'&index='+(files[0].id||0)+'&play')); else if(fi!==undefined&&fi!==null&&fi>=0)playFile(tsU('/stream/fname?link='+hash+'&index='+(files[fi].id||fi)+'&play')); else{ Lampa.Select.show({ title:'Chon file', items:files.map(function(f){return{title:(f.path||'').split('/').pop()+(f.length?' ('+(f.length/1048576).toFixed(0)+' MB)':''),value:f};}), onSelect:function(a){playFile(tsU('/stream/fname?link='+hash+'&index='+a.value.id+'&play'));}, onBack:function(){Lampa.Controller.toggle('content');} }); } }catch(e){Lampa.Noty.show('Loi TS:'+(e.message||''));} }

function showStr(streams,title,poster){ var ts=!!tsHost(); var eng=tEngine()==='aio'?'AIO':'Torrent'; Lampa.Select.show({ title:eng+':'+title+' ('+streams.length+')'+(ts?' > TS':''), items:streams.slice(0,40).map(function(s){return{title:fmtStream(s),value:s};}), onSelect:function(a){ var s=a.value; if(ts&&s.infoHash)playTS(s,title,poster,s.fileIdx); else if(s.url)Lampa.Player.play({title:title,url:s.url}); else Lampa.Noty.show(s.infoHash?'Chua cau hinh TS!':'Khong co link'); }, onBack:function(){Lampa.Controller.toggle('content');} }); }
function injectTorrentMenuCSS(){ var id='kk-torrent-menu-css'; if($('#'+id).length)return; $('head').append('<style id="'+id+'">.selectbox.selectbox-item__title{white-space:pre-wrap!important;overflow:visible!important;text-overflow:unset!important;display:block!important;}.selectbox.selectbox-item{height:auto!important;max-height:none!important;}</style>'); }

async function oTorMov(tid,title,poster,imdb){ Lampa.Noty.show('Tim torrent...'); try{ var id=imdb; if(!id){try{id=(await fetch('https://api.themoviedb.org/3/movie/'+tid+'/external_ids',{headers:{Authorization:'Bearer eyJhbGciOiJIUzI1NiJ9...'}}).then(r=>r.json())).imdb_id;}catch(e){}} if(!id){Lampa.Noty.show('Khong co IMDB');return;} var st=await fStreams('movie',id); if(!st.length){Lampa.Noty.show('Khong co stream');return;} showStr(st,title,poster); }catch(e){Lampa.Noty.show('Loi:'+(e.message||''));} }
async function oTorTV(tid,title,poster,imdb){ Lampa.Noty.show('Tai season...'); try{ var id=imdb; if(!id){try{id=(await fetch('https://api.themoviedb.org/3/tv/'+tid+'/external_ids',{headers:{Authorization:'Bearer eyJhbGciOiJIUzI1NiJ9...'}}).then(r=>r.json())).imdb_id;}catch(e){}} if(!id){Lampa.Noty.show('Khong co IMDB');return;} var sn=[]; try{ var r=await fetch('https://api.themoviedb.org/3/tv/'+tid+'?language=vi-VN'); var json=await r.json(); if(json&&json.seasons)sn=json.seasons.filter(function(s){return s.season_number>0;}).map(function(s){return{season_number:s.season_number,name:s.name||('Season '+s.season_number),episode_count:s.episode_count||0};}); }catch(e){} if(sn.length>1){ Lampa.Select.show({ title:'Chon Season', items:sn.map(function(s){return{title:s.name+(s.episode_count?' ('+s.episode_count+' tap)':''),value:s};}), onSelect:function(a){pTorEp(a.value,id,title,poster);}, onBack:function(){Lampa.Controller.toggle('content');} }); }else if(sn.length===1)pTorEp(sn[0],id,title,poster); }catch(e){Lampa.Noty.show('Loi:'+(e.message||''));} }
function pTorEp(season,imdb,title,poster){ var items=[]; for(var i=1;i<=(season.episode_count||1);i++){ items.push({title:'S'+pd(season.season_number)+'E'+pd(i),value:{s:season.season_number,e:i}}); } Lampa.Select.show({ title:season.name, items:items, onSelect:async function(a){ var lb=title+' S'+pd(a.value.s)+'E'+pd(a.value.e); Lampa.Noty.show('Tim '+lb+'...'); try{ var st=await fStreams('tv',imdb,a.value.s,a.value.e); if(!st.length){Lampa.Noty.show('Khong co');return;} showStr(st,lb,poster); }catch(e){Lampa.Noty.show('Loi:'+(e.message||''));} }, onBack:function(){Lampa.Controller.toggle('content');} }); }
async function playEpTorrent(imdbId,seasonNum,epNum,title,poster){ var lb=title+' S'+pd(seasonNum)+'E'+pd(epNum); Lampa.Noty.show('Tim torrent '+lb+'...'); try{ var st=await fStreams('tv',imdbId,seasonNum,epNum); if(!st.length){Lampa.Noty.show('Khong co stream');return;} showStr(st,lb,poster); }catch(e){Lampa.Noty.show('Loi:'+(e.message||''));} }

function bTorBtn(mt,tid,title,poster,imdb){ var eng=tEngine(); var label=eng==='aio'?'AIOStreams':'Torrent'; if(tsHost())label+=' > TS'; var css=eng==='aio'?'kk-src-btn--aio':'kk-src-btn--torrent'; var btn=$('<div class="kk-src-btn'+css+' selector" style="width:100%"><div class="kk-sb-main">'+label+'</div><div class="kk-sb-sub">Phat qua torrent</div></div>'); if(mt==='movie')bE(btn,function(){oTorMov(tid,title,poster,imdb);}); else bE(btn,function(){oTorTV(tid,title,poster,imdb);}); return $('<div style="width:100%"></div>').append(btn); }
function bE(el,fn){ var sx=0,sy=0,mv=false,tc=false; el.on('touchstart',function(e){ var t=((e.originalEvent||e).touches||[])[0]; if(t){sx=t.clientX;sy=t.clientY;mv=false;} }); el.on('touchmove',function(e){ var t=((e.originalEvent||e).touches||[])[0]; if(t&&(Math.abs(t.clientX-sx)>16||Math.abs(t.clientY-sy)>16))mv=true; }); el.on('touchend',function(e){ if(mv)return; tc=true; e.preventDefault(); e.stopPropagation(); setTimeout(function(){fn.call(el[0],e);},100); setTimeout(function(){tc=false;},350); }); el.on('click',function(e){ if(tc||mv)return; e.preventDefault(); e.stopPropagation(); fn.call(this,e); }); el.on('hover:enter',function(e){fn.call(this,e);}); }

window.KKPhimTorrent.bTorBtn = bTorBtn;
window.KKPhimTorrent.playEpTorrent = playEpTorrent;

window.__KKPhimParts.loaded.torrent = true;
console.log('[KKPhim Torrent] Loaded');
})();